[
  {
    id: "138",
    name: "Amount Description",
    status: "ACTIVE",
    groupId: null,
    displayType: "MultiLineText",
    dataType: null,
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "133",
    name: "Birthday card",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "135",
    name: "Birthday card rather than a thank you card",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "116",
    name: "Card Type",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "106",
    name: "Converted Amount",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Amount",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "107",
    name: "Converted Currency",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: [[Object]],
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "105",
    name: "Currency",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: [[Object], [Object], [Object], [Object]],
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "124",
    name: "Dedication Type",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "115",
    name: "Donation Type",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "114",
    name: "Donor Box Receipt ID",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Integer",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "112",
    name: "Donor Comment",
    status: "ACTIVE",
    groupId: null,
    displayType: "MultiLineText",
    dataType: null,
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "111",
    name: "Fee Covered",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "130",
    name: "First Donation",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "134",
    name: "Holiday card rather than a thank you card",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "125",
    name: "Honoree Name",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "131",
    name: "Hosting CTP event",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "113",
    name: "Internal Notes",
    status: "ACTIVE",
    groupId: null,
    displayType: "MultiLineText",
    dataType: null,
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "123",
    name: "Join Mailing List",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "117",
    name: "Last4",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Integer",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "137",
    name: "Make Donation Anonymous",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "132",
    name: "Mother's Day card",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "110",
    name: "Net Amount",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Amount",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "108",
    name: "Patform Fee",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Amount",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "120",
    name: "Paypal Transaction Id",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "136",
    name: "Processing Fee",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Amount",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "128",
    name: "Recipient Address",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "127",
    name: "Recipient Email",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Email",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "129",
    name: "Recipient Message",
    status: "ACTIVE",
    groupId: null,
    displayType: "MultiLineText",
    dataType: null,
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "126",
    name: "Recipient Name",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "140",
    name: "Recurring Donation",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Boolean",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "121",
    name: "Recurring Plan Id",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Integer",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "122",
    name: "Recurring Start Date",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Date",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "141",
    name: "Source",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "118",
    name: "Stripe Charge Id",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Text",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "75",
    name: "Stripe Recurring Donation",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: null,
    constituentReadOnly: false,
    component: "Donation",
    optionValues: [[Object], [Object]],
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
  {
    id: "109",
    name: "Total Fee",
    status: "ACTIVE",
    groupId: null,
    displayType: "OneLineText",
    dataType: "Amount",
    constituentReadOnly: false,
    component: "Donation",
    optionValues: null,
    isEventSpecificField: null,
    eventId: null,
    attendeeQuestion: null,
    constituentName: null,
    publicName: null,
    constituentRequired: null,
    publicRequired: null,
    constituentVisible: null,
    publicVisible: null,
  },
];
